services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Crevillo\EzTinyMCEHtmlBundle\Controller\UploadController:
        tags: ['controller.service_arguments']
        arguments:
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.location'
            - '@ezpublish.core.io.service'
            - '@ezpublish.image_alias.imagine.cache.alias_generator_decorator'
            - '@ezpublish.config.resolver'
