services:
    ezpublish.fieldType.indexable.ezhtmlblock:
        class: Crevillo\EzTinyMCEHtml\FieldType\TinyMCEHtmlBlock\SearchField
        tags:
            - {name: ezpublish.fieldType.indexable, alias: eztinymcehtmlblock}
